import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Bot,
  Check,
  CircleDollarSign,
  ExternalLink,
  Github,
  Inbox,
  MailPlus,
  RefreshCw,
  Search,
  Server,
  ShieldCheck,
  Upload
} from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { createApiClient, errorMessage, type AssistTone, type Message } from "@/api/client";
import { Toast, type ToastState } from "@/components/Toast";
import { demoMessages, fallbackDraft, filterMessages } from "@/features/mail/demo";
import { buildInfo } from "@/lib/build";
import { useLocalStorageState } from "@/lib/storage";
import { formatMailDate, relativeAge } from "@/lib/time";

const repoUrl = "https://github.com/baditaflorin/localhuman-mail";
const paypalUrl = "https://www.paypal.com/paypalme/florinbadita";
const defaultBackendUrl = import.meta.env.VITE_LOCALHUMAN_API_URL ?? "http://localhost:8080";

export function App() {
  const queryClient = useQueryClient();
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const [backendUrl, setBackendUrl] = useLocalStorageState(
    "localhuman-mail.backend-url",
    defaultBackendUrl
  );
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState(demoMessages[0]?.id ?? "");
  const [tone, setTone] = useState<AssistTone>("concise");
  const [draft, setDraft] = useState("");
  const [toast, setToast] = useState<ToastState>(null);

  const api = useMemo(() => createApiClient(backendUrl), [backendUrl]);

  const versionQuery = useQuery({
    queryKey: ["version", backendUrl],
    queryFn: async () => {
      const { data, error } = await api.GET("/api/v1/version");
      if (error || !data) throw new Error(errorMessage(error, "Backend version unavailable"));
      return data;
    },
    retry: false
  });

  const capabilitiesQuery = useQuery({
    queryKey: ["capabilities", backendUrl],
    queryFn: async () => {
      const { data, error } = await api.GET("/api/v1/capabilities");
      if (error || !data) throw new Error(errorMessage(error, "Capabilities unavailable"));
      return data.capabilities;
    },
    enabled: versionQuery.isSuccess,
    retry: false
  });

  const messagesQuery = useQuery({
    queryKey: ["messages", backendUrl],
    queryFn: async () => {
      const { data, error } = await api.GET("/api/v1/messages", {
        params: { query: { limit: 100 } }
      });
      if (error || !data) throw new Error(errorMessage(error, "Messages unavailable"));
      return data.messages;
    },
    enabled: versionQuery.isSuccess,
    retry: false
  });

  const backendOnline = versionQuery.isSuccess;
  const sourceMessages = messagesQuery.data?.length ? messagesQuery.data : demoMessages;
  const visibleMessages = filterMessages(sourceMessages, query);
  const selectedMessage =
    visibleMessages.find((message) => message.id === selectedId) ??
    visibleMessages[0] ??
    sourceMessages[0];

  const importDemoMutation = useMutation({
    mutationFn: async () => {
      const { data, error } = await api.POST("/api/v1/import/demo");
      if (error || !data) throw new Error(errorMessage(error, "Demo import failed"));
      return data;
    },
    onSuccess: async (result) => {
      setToast({ kind: "success", message: `Imported ${result.imported} demo messages` });
      await queryClient.invalidateQueries({ queryKey: ["messages", backendUrl] });
    },
    onError: (error) => {
      setToast({ kind: "error", message: errorMessage(error, "Start the backend to import demo mail") });
    }
  });

  const uploadMutation = useMutation({
    mutationFn: async (file: File) => {
      const body = new FormData();
      body.append("file", file);
      const { data, error } = await api.POST("/api/v1/import/eml", {
        body: body as never
      });
      if (error || !data) throw new Error(errorMessage(error, "EML import failed"));
      return data;
    },
    onSuccess: async (result) => {
      setToast({ kind: "success", message: `Imported ${result.imported} message` });
      await queryClient.invalidateQueries({ queryKey: ["messages", backendUrl] });
    },
    onError: (error) => {
      setToast({ kind: "error", message: errorMessage(error, "Could not import this EML file") });
    }
  });

  const assistMutation = useMutation({
    mutationFn: async (message: Message) => {
      if (!backendOnline) {
        return {
          draft: fallbackDraft(message, tone),
          model: "browser-demo",
          source: "fallback" as const
        };
      }
      const { data, error } = await api.POST("/api/v1/assist/reply", {
        body: { messageId: message.id, tone }
      });
      if (error || !data) throw new Error(errorMessage(error, "Reply assist failed"));
      return data;
    },
    onSuccess: (result) => {
      setDraft(result.draft);
      setToast({ kind: "success", message: `Draft generated by ${result.model}` });
    },
    onError: (error) => {
      setToast({ kind: "error", message: errorMessage(error, "Reply assist failed") });
    }
  });

  return (
    <main className="min-h-screen bg-paper text-ink">
      <div className="mx-auto grid min-h-screen max-w-[1500px] grid-cols-1 lg:grid-cols-[280px_minmax(420px,520px)_1fr]">
        <aside className="border-b border-line bg-white px-5 py-5 lg:border-b-0 lg:border-r">
          <div className="flex items-center gap-3">
            <span className="grid h-10 w-10 place-items-center rounded-lg bg-ink text-white">
              <Inbox aria-hidden="true" className="h-5 w-5" />
            </span>
            <div>
              <h1 className="text-lg font-semibold">localhuman-mail</h1>
              <p className="text-xs uppercase tracking-[0.18em] text-steel">private inbox AI</p>
            </div>
          </div>

          <div className="mt-7 space-y-3">
            <label className="block text-xs font-semibold uppercase tracking-[0.14em] text-steel">
              Backend
            </label>
            <div className="flex items-center gap-2 rounded-lg border border-line bg-paper px-3 py-2">
              <Server aria-hidden="true" className="h-4 w-4 text-steel" />
              <input
                aria-label="Backend URL"
                className="min-w-0 flex-1 bg-transparent text-sm outline-none"
                value={backendUrl}
                onChange={(event) => setBackendUrl(event.target.value)}
              />
            </div>
            <div className="flex items-center gap-2 text-sm">
              <span
                className={`h-2.5 w-2.5 rounded-full ${backendOnline ? "bg-fern" : "bg-coral"}`}
                aria-hidden="true"
              />
              <span>{backendOnline ? "Connected" : "Demo mode"}</span>
            </div>
          </div>

          <div className="mt-7 grid grid-cols-2 gap-2">
            <a
              className="inline-flex items-center justify-center gap-2 rounded-lg border border-line px-3 py-2 text-sm font-semibold hover:bg-paper"
              href={repoUrl}
              target="_blank"
              rel="noreferrer"
            >
              <Github aria-hidden="true" className="h-4 w-4" />
              Star
            </a>
            <a
              className="inline-flex items-center justify-center gap-2 rounded-lg border border-line px-3 py-2 text-sm font-semibold hover:bg-paper"
              href={paypalUrl}
              target="_blank"
              rel="noreferrer"
            >
              <CircleDollarSign aria-hidden="true" className="h-4 w-4" />
              PayPal
            </a>
          </div>

          <div className="mt-7 space-y-2 rounded-lg border border-line bg-paper p-3">
            <div className="flex items-center gap-2 text-sm font-semibold">
              <ShieldCheck aria-hidden="true" className="h-4 w-4 text-fern" />
              Local boundary
            </div>
            <p className="text-sm leading-6 text-steel">
              Mailbox data stays in the backend runtime store; this Pages app stores only UI settings.
            </p>
          </div>

          <dl className="mt-7 grid grid-cols-[auto_1fr] gap-x-3 gap-y-2 text-xs text-steel">
            <dt>UI</dt>
            <dd className="font-mono text-ink">v{buildInfo.version}</dd>
            <dt>Commit</dt>
            <dd className="font-mono text-ink">{buildInfo.commit}</dd>
            {versionQuery.data ? (
              <>
                <dt>API</dt>
                <dd className="font-mono text-ink">v{versionQuery.data.version}</dd>
              </>
            ) : null}
          </dl>
        </aside>

        <section className="border-b border-line bg-white lg:border-b-0 lg:border-r">
          <div className="sticky top-0 z-10 border-b border-line bg-white/95 px-4 py-4 backdrop-blur">
            <div className="flex items-center gap-2 rounded-lg border border-line bg-paper px-3 py-2">
              <Search aria-hidden="true" className="h-4 w-4 text-steel" />
              <input
                aria-label="Search messages"
                placeholder="Search mail"
                className="min-w-0 flex-1 bg-transparent text-sm outline-none"
                value={query}
                onChange={(event) => setQuery(event.target.value)}
              />
            </div>
            <div className="mt-3 flex flex-wrap items-center gap-2">
              <button
                className="inline-flex items-center gap-2 rounded-lg bg-ink px-3 py-2 text-sm font-semibold text-white hover:bg-slate-700 disabled:cursor-not-allowed disabled:opacity-60"
                type="button"
                onClick={() => importDemoMutation.mutate()}
                disabled={importDemoMutation.isPending}
              >
                <MailPlus aria-hidden="true" className="h-4 w-4" />
                Demo
              </button>
              <button
                className="inline-flex items-center gap-2 rounded-lg border border-line px-3 py-2 text-sm font-semibold hover:bg-paper"
                type="button"
                onClick={() => fileInputRef.current?.click()}
              >
                <Upload aria-hidden="true" className="h-4 w-4" />
                EML
              </button>
              <button
                className="inline-flex items-center gap-2 rounded-lg border border-line px-3 py-2 text-sm font-semibold hover:bg-paper"
                type="button"
                onClick={() => void queryClient.invalidateQueries()}
              >
                <RefreshCw aria-hidden="true" className="h-4 w-4" />
                Sync
              </button>
              <input
                ref={fileInputRef}
                className="hidden"
                type="file"
                accept=".eml,message/rfc822"
                onChange={(event) => {
                  const file = event.target.files?.[0];
                  if (file) uploadMutation.mutate(file);
                  event.currentTarget.value = "";
                }}
              />
            </div>
          </div>

          <div className="divide-y divide-line" aria-label="Message list">
            {visibleMessages.map((message) => {
              const selected = selectedMessage?.id === message.id;
              return (
                <button
                  key={message.id}
                  type="button"
                  className={`grid w-full gap-2 px-4 py-4 text-left transition hover:bg-paper ${
                    selected ? "bg-emerald-50" : "bg-white"
                  }`}
                  onClick={() => {
                    setSelectedId(message.id);
                    setDraft("");
                  }}
                >
                  <span className="flex items-center justify-between gap-3">
                    <span className="truncate text-sm font-semibold">{message.from}</span>
                    <span className="shrink-0 text-xs text-steel">{formatMailDate(message.date)}</span>
                  </span>
                  <span className="truncate text-sm font-semibold">{message.subject}</span>
                  <span className="line-clamp-2 text-sm leading-6 text-steel">{message.snippet}</span>
                  <span className="flex flex-wrap gap-1.5">
                    {message.tags.map((tag) => (
                      <span
                        key={tag}
                        className="rounded-md border border-line bg-white px-2 py-0.5 text-xs text-steel"
                      >
                        {tag}
                      </span>
                    ))}
                  </span>
                </button>
              );
            })}
          </div>
        </section>

        <section className="min-w-0 bg-white">
          {selectedMessage ? (
            <article className="grid min-h-screen grid-rows-[auto_1fr_auto]">
              <header className="border-b border-line px-5 py-5">
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <div>
                    <p className="text-sm text-steel">{relativeAge(selectedMessage.date)}</p>
                    <h2 className="mt-1 text-2xl font-semibold leading-tight">
                      {selectedMessage.subject}
                    </h2>
                  </div>
                  <a
                    className="inline-flex items-center gap-2 rounded-lg border border-line px-3 py-2 text-sm font-semibold hover:bg-paper"
                    href={repoUrl}
                    target="_blank"
                    rel="noreferrer"
                  >
                    <ExternalLink aria-hidden="true" className="h-4 w-4" />
                    GitHub
                  </a>
                </div>
                <dl className="mt-4 grid gap-2 text-sm text-steel">
                  <div className="flex gap-2">
                    <dt className="w-12 text-ink">From</dt>
                    <dd>{selectedMessage.from}</dd>
                  </div>
                  <div className="flex gap-2">
                    <dt className="w-12 text-ink">To</dt>
                    <dd>{selectedMessage.to.join(", ")}</dd>
                  </div>
                </dl>
              </header>

              <div className="overflow-auto px-5 py-6">
                <pre className="whitespace-pre-wrap font-sans text-base leading-7 text-ink">
                  {selectedMessage.body}
                </pre>
              </div>

              <footer className="border-t border-line bg-paper px-5 py-4">
                <div className="flex flex-wrap items-center gap-2">
                  {(["concise", "warm", "decisive"] as const).map((item) => (
                    <button
                      key={item}
                      type="button"
                      className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold capitalize ${
                        tone === item ? "border-fern bg-emerald-50 text-fern" : "border-line bg-white"
                      }`}
                      onClick={() => setTone(item)}
                    >
                      {tone === item ? <Check aria-hidden="true" className="h-4 w-4" /> : null}
                      {item}
                    </button>
                  ))}
                  <button
                    type="button"
                    className="inline-flex items-center gap-2 rounded-lg bg-fern px-3 py-2 text-sm font-semibold text-white hover:bg-emerald-800 disabled:cursor-not-allowed disabled:opacity-60"
                    disabled={assistMutation.isPending}
                    onClick={() => assistMutation.mutate(selectedMessage)}
                  >
                    <Bot aria-hidden="true" className="h-4 w-4" />
                    Draft
                  </button>
                </div>
                {draft ? (
                  <textarea
                    aria-label="Generated reply draft"
                    className="mt-3 min-h-36 w-full resize-y rounded-lg border border-line bg-white p-3 text-sm leading-6 outline-none focus:border-fern"
                    value={draft}
                    onChange={(event) => setDraft(event.target.value)}
                  />
                ) : null}
              </footer>
            </article>
          ) : (
            <div className="grid min-h-screen place-items-center px-6 text-center text-steel">
              <p>No messages found.</p>
            </div>
          )}
        </section>
      </div>
      <Toast toast={toast} />
      <div className="sr-only" aria-live="polite">
        {versionQuery.isFetching || messagesQuery.isFetching || capabilitiesQuery.isFetching
          ? "Refreshing"
          : "Idle"}
      </div>
    </main>
  );
}

